"""address status

Revision ID: 873ad83450bf
Revises: 1af329e1ba61
Create Date: 2025-06-16 23:23:20.313642

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "873ad83450bf"
down_revision: Union[str, None] = "1af329e1ba61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("address", sa.Column("status", sa.Enum("PENDING", "ACCEPTED", "REJECTED", name="addressstatus"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("address", "status")
    # ### end Alembic commands ###
