"""Init db

Revision ID: 021510330a95
Revises:
Create Date: 2025-06-03 00:18:20.189137

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "021510330a95"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "address",
        sa.Column("address_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("living_zone_type", sa.Enum("VILLAGE", "CITY", name="lzaddresstypes"), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("street", sa.String(), nullable=False),
        sa.Column("district", sa.String(), nullable=True),
        sa.Column("postal_code", sa.String(), nullable=False),
        sa.Column("extras", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("address_id"),
    )
    op.create_index(op.f("ix_address_district"), "address", ["district"], unique=False)
    op.create_index(op.f("ix_address_name"), "address", ["name"], unique=False)
    op.create_index(op.f("ix_address_postal_code"), "address", ["postal_code"], unique=False)
    op.create_index(op.f("ix_address_state"), "address", ["state"], unique=False)
    op.create_index(op.f("ix_address_street"), "address", ["street"], unique=False)
    op.create_table(
        "living_zone",
        sa.Column("lz_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("property_type", sa.Enum("DISTRICT", "VILLAGE", "CITY", "STREET", name="lztypes"), nullable=False),
        sa.Column("parent_zone_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_zone_id"],
            ["living_zone.lz_id"],
        ),
        sa.PrimaryKeyConstraint("lz_id"),
    )
    op.create_index(op.f("ix_living_zone_name"), "living_zone", ["name"], unique=False)
    op.create_table(
        "building",
        sa.Column("building_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("lz_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("address_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "building_type",
            sa.Enum("APARTMENT", "OFFICE", "PRIVATE_HOUSE", "SHOPPING_MAIL", "MIXED_USE", name="buildingtype"),
            nullable=False,
        ),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["address_id"],
            ["address.address_id"],
        ),
        sa.ForeignKeyConstraint(
            ["lz_id"],
            ["living_zone.lz_id"],
        ),
        sa.PrimaryKeyConstraint("building_id"),
    )
    op.create_index(op.f("ix_building_name"), "building", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_building_name"), table_name="building")
    op.drop_table("building")
    op.drop_index(op.f("ix_living_zone_name"), table_name="living_zone")
    op.drop_table("living_zone")
    op.drop_index(op.f("ix_address_street"), table_name="address")
    op.drop_index(op.f("ix_address_state"), table_name="address")
    op.drop_index(op.f("ix_address_postal_code"), table_name="address")
    op.drop_index(op.f("ix_address_name"), table_name="address")
    op.drop_index(op.f("ix_address_district"), table_name="address")
    op.drop_table("address")
    # ### end Alembic commands ###
